removing dependeny to WinLaF because of errors in newer Java versions: http://www.jabaco.org/board/629-error-java-lang-nosuchmethoderror.html http://www.jabaco.org/board/258-error-starting-application.html